"""user table

Revision ID: 0607a2129db2
Revises: 3344a732e654
Create Date: 2022-05-20 15:04:59.392322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0607a2129db2'
down_revision = '3344a732e654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('sub_title', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('time_posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_time_posted'), 'blog', ['time_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_time_posted'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
